### PR TITLE
Fix: IPV4 can't display on zipkin server

### PR DESCRIPTION
**Pull request by fedj**
fix the problem mentioned here
#165

### CODE REVIEW

**Comment by fedj** [comment]
cc @anthonywanted

**Comment by codefromthecrypt** [comment]
I might name the function ipLiteral or similar, as pure is kindof more
interesting than you might intend ;)

**Comment by fedj** [comment]
@adriancole Done, @anthonywanted I'm sorry to change your commit but it will be quicker to be merged that way

**Comment by anthonywanted** [comment]
Never mind :)

**Pull request merged**
