### PR TITLE
Fix the handler to allow it usage with httpclientfactory

### PR DESCRIPTION
**Pull request by bhugot**

### CODE REVIEW

**Comment by fedj** [comment]
Hi @bhugot,

Can you explain why you are removing the InnerHandler as I'm not sure to understand the context?

**Comment by bhugot** [comment]
Because aspnetcore httpclientfactory doesn t work if there is a inner

**Comment by fedj** [comment]
From what I remember, the example won't work if there's no InnerHandler. Did you run the aspnetcore example ?

**Comment by bhugot** [comment]
Yes and I pushed the change so you can try it also

**Comment by bhugot** [comment]
new version is better and not breaking the inner handler approch

**Comment by fedj** [comment]
Indeed, I think it's way better to keep the backward compatibility. Can I nitpick and ask you to add comments on these two methods, most notably withoutInnerHandler as it can be confusing?

**Comment by bhugot** [comment]
Is it ok for you?

**Comment by fedj** [comment]
LGTM

**Comment by fedj** [comment]
Thanks a lot @bhugot !

**Comment by bhugot** [comment]
Np any luck you release it soon?

**Comment by fedj** [comment]
I'll do it now

**Comment by bhugot** [comment]
thx

**Comment by fedj** [comment]
https://www.nuget.org/packages/zipkin4net/1.2.3 has been released on Friday btw

**Pull request merged**
