### PR TITLE
Fixed multi-targeting for net45

### PR DESCRIPTION
**Pull request by aliostad**
Turns out no need to have to separate csproj file. A single csproj with multi-targeting works really well.

This is not an invasive PR, very few changes but the build completely works now targeting both .NET 4.5 and newer stuff.

### CODE REVIEW

**Comment by aliostad** [comment]
The reason build has failed is that the Travis host does not have .NET Framework 4.5.
If you want I can fix that as well but frankly has got no communication back.

**Comment by codefromthecrypt** [comment]
I'd guess build green is a prerequisite. I did a little digging, but am unfamiliar with the platform. Hope the below help anyway:

This question about travis includes "matrix build" instructions (this allows you to run the same tests against different versions and get a different report) https://stackoverflow.com/questions/16751772/how-do-i-use-travis-ci-with-c-sharp-or-f

If for some reason travis can't work, one approach we take in other zipkin projects is to use another build monitor for the other platform (ex we have some projects that use circleci by default and then travis for docker). Appveyor may be helpful, and here's a link on it http://help.appveyor.com/discussions/questions/3404-appveyor-not-detecting-netstandard-core-project-in-multi-project-solution

I understand this research may not be helpful, but since I'm awake a lot earlier than others due to timezone, hope it can at least prep.

**Comment by fedj** [comment]
Hi @aliostad,

I'm sorry, I was out for the weekend for a wedding and I didn't know that was so urgent to you.
Anyway, I really think that no one should introduce a broken build to master. Hence, it's kind of a precondition to get the build green to be able to be merged.

As a first look on google, I did find https://stackoverflow.com/questions/44770702/build-nuget-package-on-linux-that-targets-net-framework/44773795#44773795 which seems to solve the issue

**Comment by aliostad** [comment]
>  really think that no one should introduce a broken build to master

Fair enough, hope you had a good time.

**Pull request closed without merging**
