### PR TITLE
Fix TraceId not in lower case

### PR DESCRIPTION
**Pull request by klettier**
Hello,

I'm getting **IllegalArgumentException** on **TraceId** field with the current **master** version of the code (not the package).

Here is the the fix that just call the right function in **JSONSpanSerializer**

Regards,

kévin

### CODE REVIEW

**Comment by crntn** [comment]
Hi @klettier !
Thank you for your pull request, I believe this will also fix #99.

**Review by crntn — APPROVED** [review]
Good catch, thanks !

**Comment by codefromthecrypt** [comment]
thank you! will follow-up to make sure error messages on the server are better

**Comment by klettier** [comment]
@adriancole For me the error in the console was quite obvious as it mention the payload and the field concerned by the error

**Pull request merged**
