### PR TITLE
add meaningful http tags in tracing handler

### PR DESCRIPTION
**Pull request by bvillanueva-mdsol**
add meaningful tag information in tracing handler to be logged in client trace span

Example client span:
```json
{
    "traceId": "32fbe6aebee305d6",
    "parentId": "9226c0ff90576f24",
    "id": "45ac2aef4e520137",
    "kind": "CLIENT",
    "name": "post",
    "timestamp": 1585705152801537,
    "duration": 2271648,
    "localEndpoint": {
        "serviceName": "xxx.com",
        "ipv4": "10.152.25.184"
    },
    "tags": {
        "http.host": "yyy.com",
        "http.method": "POST",
        "http.path": "/index",
        "http.status_code": "200"
    }
}
```

Please review and merge.
@adriancole @jcarres-mdsol 

FYI @kfurue-mdsol @ykitamura-mdsol @sleeloy-mdsol @lschreck-mdsol

### CODE REVIEW

**Comment by jcarres-mdsol** [comment]
@adriancole  does it sound right?

**Comment by codefromthecrypt** [comment]
by default we usually don't add host. also only non-success status codes. otherwise sounds good!

**Comment by bvillanueva-mdsol** [comment]
Added code to only log non-success status codes and unit tests too 66c64a1
@adriancole @jcarres-mdsol

**Comment by codefromthecrypt** [comment]
thanks
for the host it can be high cardinality so probably not default tag. cool
to make optional though

**Comment by bvillanueva-mdsol** [comment]
Thanks for the advice. Add option to log http host with unit test 
2605829
@adriancole @jcarres-mdsol

**Review by codefromthecrypt — APPROVED** [review]

**Pull request merged**
