### PR TITLE
allow to configure what will be the rpc used

### PR DESCRIPTION
**Pull request by bhugot**
Hello,

we found that only have HttpMethod as rpc is mostly useless specialy at tracingHandler level.
This allow us to configure as we want what we put in rpc.

### CODE REVIEW

**Comment by fedj** [comment]
Hello,
Thanks a lot for the PR. It seems like a nice abstraction.
Would you have the time to push a PR for a gRpc transport project ?

**Comment by fedj** [comment]
@bhugot, introduced test seems to be random on appVeyor. Would you have time to have a look ? https://ci.appveyor.com/project/fedj/zipkin4net/build/100

**Comment by bhugot** [comment]
@fedj, I will look at it but it strange as it's same test  than the existing one for Get. but as the tests are playing with delay it can occur that at one time the machine was slow? could you retry the build?

**Comment by bhugot** [comment]
got same error with the previous version https://ci.appveyor.com/project/bhugot/zipkin4net/build/1

**Comment by fedj** [comment]
Oh. Fair enough. I'll try to debug to see what's wrong

**Comment by bhugot** [comment]
I will look at it also. Any ETA on a new release?

**Comment by fedj** [comment]
1.2.0 in progress

**Comment by fedj** [comment]
#189 merged

**Comment by fedj** [comment]
1.2.0 published on nuget.org

**Pull request merged**
