### PR TITLE
Owin middleware release

### PR DESCRIPTION
**Pull request by klettier**
Hello,

Could you please publish Owin middleware nuget package ?

Thanks,

kévin

### CODE REVIEW

**Comment by fedj** [comment]
Hi @klettier,

It seems there is a unit test failing. I'm not sure why yet but I'll try to find out quickly as it blocks the release of your nuget. If you have any idea/suggestion that comes to your mind, don't hesitate to push another commit on this PR.

**Comment by fedj** [comment]
#167 should fix it. Can you rebase ?

**Comment by klettier** [comment]
Thank you, any chance to have a release soon ?

**Comment by fedj** [comment]
@klettier Thanks a lot for your help! Here it is:

https://www.nuget.org/packages/zipkin4net.middleware.owin/1.1.1

**Pull request merged**
