### PR TITLE
Feature/build2

### PR DESCRIPTION
**Pull request by klettier**
Related to #144 #122 #143 

Generic solution for building and testing

### CODE REVIEW

**Comment by klettier** [comment]
Hello, any updates on this?

Thanks

**Comment by crntn** [comment]
Hi @klettier  !
This is awesome. The only comment I have would be to document the build in the readme (either in this PR or another one)  so that new users to necessarily have to explore build.fsx the first time they interact with zipkin4net.

**Review by crntn — APPROVED** [review]

**Comment by fedj** [comment]
Thanks a lot for this review @klettier, sorry for the delay

**Comment by klettier** [comment]
Hello guys, thank you for the merge :)

The documentation for the build will come with the PR to produce the Owin Middleware nuget package ;)

**Pull request merged**
